### ISSUE TITLE
The documentation for this GS is incorrect in places.

### ISSUE THREAD

**Issue by cvanburen** [spring-guides/gs-testing-web#2]
As of 8/30/2016:

I downloaded content into Eclipse with "Import Spring Getting Started Content" for "Testing Web".  The document that was displayed included text that references draft-gs-template instead of gs-testing-web.  For example:
...
•Download and unzip the source repository for this guide, or clone it using Git: git clone https://github.com/spring-guides/draft-gs-template.git
There are more references to draft...

Also, web page has these include statements where code should be displayed: 
...
src/test/java/hello/SmokeTest.java
include::complete/src/test/java/hello/SmokeTest.java
...
src/test/java/hello/HttpRequestTest.java
include::complete/src/test/java/hello/HttpRequestTest.java
...
src/test/java/hello/ApplicationTest.java
include::complete/src/test/java/hello/ApplicationTest.java

**Comment by gregturn** [comment]
There's a tag in README.adoc that needs to fixed. If you're willing to patch it that would be appreciated.

**Comment by dsyer** [comment]
Fixed in 08b22fdf78726eebd946c93aaa2ca51db73ef919. Thanks.
