### ISSUE TITLE
make sure you are requestiong the right URl. For example if in your Restcontroller you have defined this : @RequestMapping("/")

### ISSUE THREAD

**Issue by ghost** [spring-guides/gs-testing-web#28]
make sure you are requestiong the right URl. For example if in your Restcontroller you have defined this : @RequestMapping("/")
	    public String index() {
	        return "Greetings from Spring Boot!";
	    }

your URL must be like "http://localhost:8080/" because of the @RequestMapping("/")

I hope this was helpful 

_Originally posted by @sassoura in https://github.com/spring-projects/spring-boot/issues/9371#issuecomment-324463226_

**Comment by adilwahla** [comment]
still getting same issue
