### ISSUE TITLE
Missing complete/src/test/java/hello/SmokeTest.java

### ISSUE THREAD

**Issue by butzopower** [spring-guides/gs-testing-web#3]
It seems like the file `complete/src/test/java/hello/SmokeTest.java` is missing and so it doesn't render properly in the guide.  Here's how it is showing up:

<img width="717" alt="screen shot 2016-09-12 at 4 41 53 pm" src="https://cloud.githubusercontent.com/assets/5345/18456825/07e69828-7909-11e6-9caf-54820d705589.png">

**Comment by dsyer** [comment]
Thanks. Should be fixed in 352348c.
